### PR TITLE
es6 support

### PR DESCRIPTION
**Pull request by celesteking**
How about this, if we go ES6 route?

### CODE REVIEW

**Comment by msimerson** [comment]
We are going the ES6 route. Please rebase against master.

**Comment by msimerson** [comment]
Also update Changes file.

**Comment by celesteking** [comment]
Shall I verbump the patch or shall we make another minor - say 1.1.0?

**Comment by msimerson** [comment]
I haven't published yet, so no need to bump.

**Comment by msimerson** [comment]
And we aren't changing our API, so no need to bump minor.

**Comment by msimerson** [comment]
I do wonder if we should add this to package.json?

```json
  "engines": {
    "node": ">= v10.17.0"
  },
```

**Comment by msimerson** [comment]
that would notify users that their no-longer-maintained v8 isn't "good enough" any more.

**Comment by celesteking** [comment]
It looks like it's used not only by Haraka, so yes.

**Comment by msimerson** [comment]
Then please do the needful. :-)

**Review by msimerson — APPROVED** [review]

**Pull request merged**
